CHERRY/CHERRY/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account'))
]

CHERRY/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register', views.UserRegisterView.as_view(), name='user_register'),
    path('login', views.UserLoginView.as_view(), name='user_login'),
    path('logout', views.UserLogoutView.as_view(), name='user_logout'),
]

CHERRY/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

CHERRY/account/models.py
from django.db import models

# Create your models here.

CHERRY/home/models.py
from django.db import models

# Create your models here.

CHERRY/account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from phonenumber_field.formfields import PhoneNumberField


class UserRegistrationForm(forms.Form):
    username = PhoneNumberField(label='شماره‌موبایل',  widget=forms.TextInput(
        attrs={'class': 'form-control eng'}), error_messages={
        'invalid': 'فرمت شماره‌موبایل نادرست است. فرمت درست: +989123456789 یا 09123456789'
    })
    email = forms.EmailField(label='ایمیل', widget=forms.EmailInput(
        attrs={'class': 'form-control eng'}), error_messages={
            'invalid': 'ساختار ایمیل نادرست است.'
    })
    password = forms.CharField(label='کلمه عبور', widget=forms.PasswordInput(
        attrs={'class': 'form-control eng'}))
    confirm_password = forms.CharField(label='تکرار کلمه عبور', widget=forms.PasswordInput(
        attrs={'class': 'form-control eng'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError(message='این ایمیل تکراری است.')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        print(username)
        # if username.startswith('0'):
        #     username = username.replace('0', '+98', 1)
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('شماره‌موبایل تکراری است.')
        return username

    def clean(self):
        cd = super().clean()
        password = cd.get('password')
        confirm_password = cd.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise ValidationError('کلمه عبور و تکرار آن با هم یکی نیستند!')


class UserLoginForm(forms.Form):
    username = PhoneNumberField(label='شماره‌موبایل',  widget=forms.TextInput(
        attrs={'class': 'form-control eng'}), error_messages={
        'invalid': 'فرمت شماره‌موبایل نادرست است. فرمت درست: +989123456789 یا 09123456789'
    })
    password = forms.CharField(label='کلمه عبور', widget=forms.PasswordInput(
        attrs={'class': 'form-control eng'}))

CHERRY/account/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'account/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if(form.is_valid()):
            cd = form.cleaned_data
            User.objects.create_user(
                cd['username'], cd['email'], cd['password'])
            messages.success(
                request, 'ثبت نام با موفقیت انجام شد.', extra_tags='success')
            return redirect('home:home')
        messages.error(
            request, 'ابتدا اطلاعات را به درستی تکمیل نمایید.', extra_tags='danger')
        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'account/login.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'با موفقیت وارد شدید', 'success')
                return redirect('home:home')
            messages.error(request, 'نام کاربری یا کلمه عبور اشتباه است.')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(View):

    def get(self, request):
        logout(request)
        messages.success(request, 'با موفقیت از سامانه خارج شدید', 'success')
        return redirect('home:home')

CHERRY/home/views.py
from django.shortcuts import render
from django.views import View


class HomeView(View):
    def get(self, request):
        return render(request, 'home/index.html')

CHERRY/home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}صفحه اصلی{% endblock %}

{% block content %}
<h3>خوش آمدید به گیلاس</h3>

{% endblock %}

CHERRY/templates/base.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>شبکه اجتماعی گیلاس -
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.rtl.min.css"
              integrity="sha384-dc2NSrAXbAkjrdm9IYrX10fQq9SDG6Vjz7nQVKdKcJl3pC+k37e7qJR5MVSCS+wR"
              crossorigin="anonymous"/>
        <style>
            .eng{
                direction: ltr;
                text-align:left;
            }
        </style>
    </head>
    <body>
        {% include 'inc/navbar.html' %}
        <div class="container-fluid">
            <div class="row content">
                <div class="col-12 p-5 mb-4 bg-light rounded-3">
                    {% include 'inc/messages.html' %}
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </body>
</html>

CHERRY/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}<p class="alert alert-{{ msg.tags }}">{{ msg }}</p>{% endfor %}
{% endif %}

CHERRY/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">شبکه اجتماعی گیلاس</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">صفحه اصلی</a>
                </li>
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_register' %}">ثبت نام</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_login' %}">ورود</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_logout' %}">خروج</a>
                    </li>
                    <li class="nav-item" style="color:white;">
                        <a class="nav-link" href="#">
                        {{ request.user.first_name }} {{ request.user.last_name }}
                            
                        </a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</nav>